### ISSUE TITLE
Unable to mark large images in Android

### ISSUE THREAD

**Issue by ssafayet** [JimmyDaddy/react-native-image-marker#237]
I am using react-native-image-marker version 1.1.5 with rn version 0.72. Whenever I try to mark a large high-resolution image with a logo, it fails to do so. It also throws the following errors:

09-15 15:22:04.462 10038 11581 E ImageLoader: Failed to load image: file:///data/user/0/com.packagename/cache/ReactNative_cropped_image_4249913402974771055.jpg
09-15 15:22:04.462 10038 11581 E ImageLoader: java.util.concurrent.ExecutionException: com.jimmydaddy.imagemarker.base.MarkerError
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:372)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2049)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at com.jimmydaddy.imagemarker.ImageLoader$loadImages$2$deferredList$1$1.invokeSuspend(ImageLoader.kt:77)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
09-15 15:22:04.462 10038 11581 E ImageLoader: Caused by: com.jimmydaddy.imagemarker.base.MarkerError
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at com.jimmydaddy.imagemarker.ImageLoader$loadImages$2$deferredList$1$1$1.onFailureImpl(ImageLoader.kt:73)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at com.facebook.datasource.BaseDataSubscriber.onFailure(BaseDataSubscriber.java:62)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:196)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-15 15:22:04.462 10038 11581 E ImageLoader: 	at java.lang.Thread.run(Thread.java:1012)
09-15 15:22:04.464 10038 10038 W System.err: java.lang.NullPointerException
09-15 15:22:04.464 10038 10038 W System.err: 	at com.jimmydaddy.imagemarker.ImageMarkerManager.markImageByBitmap(ImageMarkerManager.kt:59)
09-15 15:22:04.464 10038 10038 W System.err: 	at com.jimmydaddy.imagemarker.ImageMarkerManager.access$markImageByBitmap(ImageMarkerManager.kt:36)
09-15 15:22:04.465 10038 10038 W System.err: 	at com.jimmydaddy.imagemarker.ImageMarkerManager$markWithImage$1.invokeSuspend(ImageMarkerManager.kt:265)
09-15 15:22:04.465 10038 10038 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-15 15:22:04.465 10038 10038 W System.err: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
09-15 15:22:04.465 10038 10038 W System.err: 	at android.os.Handler.handleCallback(Handler.java:959)
09-15 15:22:04.465 10038 10038 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-15 15:22:04.465 10038 10038 W System.err: 	at android.os.Looper.loopOnce(Looper.java:232)
09-15 15:22:04.466 10038 10038 W System.err: 	at android.os.Looper.loop(Looper.java:317)
09-15 15:22:04.466 10038 10038 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8592)
09-15 15:22:04.466 10038 10038 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-15 15:22:04.466 10038 10038 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
09-15 15:22:04.466 10038 10038 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

It works for smaller images (like images less than 1mb).

**Devlopment environment(please complete the following information):**
 - OS: OSX
 - nodejs: 18
 - react-native: 0.72
 - react-native-image-marker :  1.1.15

**Comment by ssafayet** [comment]
The issue is fixed in the latest version of the library. Had to update react native.
